### ISSUE TITLE
Support the configuration file

### ISSUE THREAD

**Issue by hidakatsuya** [hidakatsuya/redmined#4]
```
/path/to/redmine/
  .redmined.yml
  app/
  ...
  README.md
```

.redmined.yml
```yml
# Basic settings
# ---

# This name determines to the following settings:
#   * bundle_cache_volume -> "redmined-<name>-bundle-cache"
#   * container_name -> "redmined-<name>-container" 
name: "redmine"

# This version determines the container image redmined uses
#    * ghcr.io/hidakatsuya/redmined:<ruby-version> (Internally the version affects to $REDMINED_IMAGE)
ruby_version: "3.3"

# This port determines the "--export" settings of `docker run` and $PORT which `rails server` respects
#   * docker run -p "<port>:<port>" (Internally the port affetcts to $REDMINED_PUBLISH_PORT)
#   * $PORT=<port>
port: 3000

# Set environment variables in the container
env:
  PUMA_MIN_THREADS: 1
```

The following settings won't be implemented in the first release of thi feature.
```yml
# Advanced settings
# ---
# https://github.com/hidakatsuya/redmined/blob/main/redmined
#
container_name: "container_name"
map_host_user_to_container_user: true
bundle_cache_volume: "volume_name"
image: "image_name"
publish_port: "3000:3000"
```

**Comment by hidakatsuya** [comment]
Is the ability to set up multiple environments?

```yml
default:
  name: "redmine"
  ruby_version: "3.3"

ruby32:
  name: "redmine-with-ruby32"
  ruby_version: "3.2"
```

```shell
$ redmined ruby -v
Ruby 3.3

$ redmined ruby32
Ruby 3.2
```

Or, `redmined` supports "--config /path/to/config.yml"?

```
/path/to/redmine/
  .redmined/
    config.yml
    other_config.yml
```
```
$ redmined --config .redmined/other_config.yml ruby -v
```
